[MeterBar0]
Meter=BAR
BarColor=FAFAFA
MeasureName=MeasureAudioSmoothed1
X=(6 * 1)R
Y=0
W=(6 * 1)
H=(864 * 0.25)
BarOrientation=Vertical
[MeterBar1]
Meter=BAR
BarColor=FAFAFA
MeasureName=MeasureAudioSmoothed2
X=(6 * 1)R
Y=0
W=(6 * 1)
H=(864 * 0.25)
BarOrientation=Vertical
[MeterBar2]
Meter=BAR
BarColor=FAFAFA
MeasureName=MeasureAudioSmoothed3
X=(6 * 1)R
Y=0
W=(6 * 1)
H=(864 * 0.25)
BarOrientation=Vertical
[MeterBar3]
Meter=BAR
BarColor=FAFAFA
MeasureName=MeasureAudioSmoothed4
X=(6 * 1)R
Y=0
W=(6 * 1)
H=(864 * 0.25)
BarOrientation=Vertical
[MeterBar4]
Meter=BAR
BarColor=FAFAFA
MeasureName=MeasureAudioSmoothed5
X=(6 * 1)R
Y=0
W=(6 * 1)
H=(864 * 0.25)
BarOrientation=Vertical
[MeterBar5]
Meter=BAR
BarColor=FAFAFA
MeasureName=MeasureAudioSmoothed6
X=(6 * 1)R
Y=0
W=(6 * 1)
H=(864 * 0.25)
BarOrientation=Vertical
[MeterBar6]
Meter=BAR
BarColor=FAFAFA
MeasureName=MeasureAudioSmoothed7
X=(6 * 1)R
Y=0
W=(6 * 1)
H=(864 * 0.25)
BarOrientation=Vertical
[MeterBar7]
Meter=BAR
BarColor=FAFAFA
MeasureName=MeasureAudioSmoothed8
X=(6 * 1)R
Y=0
W=(6 * 1)
H=(864 * 0.25)
BarOrientation=Vertical
[MeterBar8]
Meter=BAR
BarColor=FAFAFA
MeasureName=MeasureAudioSmoothed9
X=(6 * 1)R
Y=0
W=(6 * 1)
H=(864 * 0.25)
BarOrientation=Vertical
[MeterBar9]
Meter=BAR
BarColor=FAFAFA
MeasureName=MeasureAudioSmoothed10
X=(6 * 1)R
Y=0
W=(6 * 1)
H=(864 * 0.25)
BarOrientation=Vertical
[MeterBar10]
Meter=BAR
BarColor=FAFAFA
MeasureName=MeasureAudioSmoothed11
X=(6 * 1)R
Y=0
W=(6 * 1)
H=(864 * 0.25)
BarOrientation=Vertical
[MeterBar11]
Meter=BAR
BarColor=FAFAFA
MeasureName=MeasureAudioSmoothed12
X=(6 * 1)R
Y=0
W=(6 * 1)
H=(864 * 0.25)
BarOrientation=Vertical
[MeterBar12]
Meter=BAR
BarColor=FAFAFA
MeasureName=MeasureAudioSmoothed13
X=(6 * 1)R
Y=0
W=(6 * 1)
H=(864 * 0.25)
BarOrientation=Vertical
[MeterBar13]
Meter=BAR
BarColor=FAFAFA
MeasureName=MeasureAudioSmoothed14
X=(6 * 1)R
Y=0
W=(6 * 1)
H=(864 * 0.25)
BarOrientation=Vertical
[MeterBar14]
Meter=BAR
BarColor=FAFAFA
MeasureName=MeasureAudioSmoothed15
X=(6 * 1)R
Y=0
W=(6 * 1)
H=(864 * 0.25)
BarOrientation=Vertical
[MeterBar15]
Meter=BAR
BarColor=FAFAFA
MeasureName=MeasureAudioSmoothed16
X=(6 * 1)R
Y=0
W=(6 * 1)
H=(864 * 0.25)
BarOrientation=Vertical
[MeterBar16]
Meter=BAR
BarColor=FAFAFA
MeasureName=MeasureAudioSmoothed17
X=(6 * 1)R
Y=0
W=(6 * 1)
H=(864 * 0.25)
BarOrientation=Vertical
[MeterBar17]
Meter=BAR
BarColor=FAFAFA
MeasureName=MeasureAudioSmoothed18
X=(6 * 1)R
Y=0
W=(6 * 1)
H=(864 * 0.25)
BarOrientation=Vertical
[MeterBar18]
Meter=BAR
BarColor=FAFAFA
MeasureName=MeasureAudioSmoothed19
X=(6 * 1)R
Y=0
W=(6 * 1)
H=(864 * 0.25)
BarOrientation=Vertical
[MeterBar19]
Meter=BAR
BarColor=FAFAFA
MeasureName=MeasureAudioSmoothed20
X=(6 * 1)R
Y=0
W=(6 * 1)
H=(864 * 0.25)
BarOrientation=Vertical
[MeterBar20]
Meter=BAR
BarColor=FAFAFA
MeasureName=MeasureAudioSmoothed21
X=(6 * 1)R
Y=0
W=(6 * 1)
H=(864 * 0.25)
BarOrientation=Vertical
[MeterBar21]
Meter=BAR
BarColor=FAFAFA
MeasureName=MeasureAudioSmoothed22
X=(6 * 1)R
Y=0
W=(6 * 1)
H=(864 * 0.25)
BarOrientation=Vertical
[MeterBar22]
Meter=BAR
BarColor=FAFAFA
MeasureName=MeasureAudioSmoothed23
X=(6 * 1)R
Y=0
W=(6 * 1)
H=(864 * 0.25)
BarOrientation=Vertical
[MeterBar23]
Meter=BAR
BarColor=FAFAFA
MeasureName=MeasureAudioSmoothed24
X=(6 * 1)R
Y=0
W=(6 * 1)
H=(864 * 0.25)
BarOrientation=Vertical
[MeterBar24]
Meter=BAR
BarColor=FAFAFA
MeasureName=MeasureAudioSmoothed25
X=(6 * 1)R
Y=0
W=(6 * 1)
H=(864 * 0.25)
BarOrientation=Vertical
[MeterBar25]
Meter=BAR
BarColor=FAFAFA
MeasureName=MeasureAudioSmoothed26
X=(6 * 1)R
Y=0
W=(6 * 1)
H=(864 * 0.25)
BarOrientation=Vertical
[MeterBar26]
Meter=BAR
BarColor=FAFAFA
MeasureName=MeasureAudioSmoothed27
X=(6 * 1)R
Y=0
W=(6 * 1)
H=(864 * 0.25)
BarOrientation=Vertical
[MeterBar27]
Meter=BAR
BarColor=FAFAFA
MeasureName=MeasureAudioSmoothed28
X=(6 * 1)R
Y=0
W=(6 * 1)
H=(864 * 0.25)
BarOrientation=Vertical
[MeterBar28]
Meter=BAR
BarColor=FAFAFA
MeasureName=MeasureAudioSmoothed29
X=(6 * 1)R
Y=0
W=(6 * 1)
H=(864 * 0.25)
BarOrientation=Vertical
[MeterBar29]
Meter=BAR
BarColor=FAFAFA
MeasureName=MeasureAudioSmoothed30
X=(6 * 1)R
Y=0
W=(6 * 1)
H=(864 * 0.25)
BarOrientation=Vertical
[MeterBar30]
Meter=BAR
BarColor=FAFAFA
MeasureName=MeasureAudioSmoothed31
X=(6 * 1)R
Y=0
W=(6 * 1)
H=(864 * 0.25)
BarOrientation=Vertical
[MeterBar31]
Meter=BAR
BarColor=FAFAFA
MeasureName=MeasureAudioSmoothed32
X=(6 * 1)R
Y=0
W=(6 * 1)
H=(864 * 0.25)
BarOrientation=Vertical
[MeterBar32]
Meter=BAR
BarColor=FAFAFA
MeasureName=MeasureAudioSmoothed33
X=(6 * 1)R
Y=0
W=(6 * 1)
H=(864 * 0.25)
BarOrientation=Vertical
[MeterBar33]
Meter=BAR
BarColor=FAFAFA
MeasureName=MeasureAudioSmoothed34
X=(6 * 1)R
Y=0
W=(6 * 1)
H=(864 * 0.25)
BarOrientation=Vertical
[MeterBar34]
Meter=BAR
BarColor=FAFAFA
MeasureName=MeasureAudioSmoothed35
X=(6 * 1)R
Y=0
W=(6 * 1)
H=(864 * 0.25)
BarOrientation=Vertical
[MeterBar35]
Meter=BAR
BarColor=FAFAFA
MeasureName=MeasureAudioSmoothed36
X=(6 * 1)R
Y=0
W=(6 * 1)
H=(864 * 0.25)
BarOrientation=Vertical
[MeterBar36]
Meter=BAR
BarColor=FAFAFA
MeasureName=MeasureAudioSmoothed37
X=(6 * 1)R
Y=0
W=(6 * 1)
H=(864 * 0.25)
BarOrientation=Vertical
[MeterBar37]
Meter=BAR
BarColor=FAFAFA
MeasureName=MeasureAudioSmoothed38
X=(6 * 1)R
Y=0
W=(6 * 1)
H=(864 * 0.25)
BarOrientation=Vertical
[MeterBar38]
Meter=BAR
BarColor=FAFAFA
MeasureName=MeasureAudioSmoothed39
X=(6 * 1)R
Y=0
W=(6 * 1)
H=(864 * 0.25)
BarOrientation=Vertical
[MeterBar39]
Meter=BAR
BarColor=FAFAFA
MeasureName=MeasureAudioSmoothed40
X=(6 * 1)R
Y=0
W=(6 * 1)
H=(864 * 0.25)
BarOrientation=Vertical
[MeterBar40]
Meter=BAR
BarColor=FAFAFA
MeasureName=MeasureAudioSmoothed41
X=(6 * 1)R
Y=0
W=(6 * 1)
H=(864 * 0.25)
BarOrientation=Vertical
[MeterBar41]
Meter=BAR
BarColor=FAFAFA
MeasureName=MeasureAudioSmoothed42
X=(6 * 1)R
Y=0
W=(6 * 1)
H=(864 * 0.25)
BarOrientation=Vertical
[MeterBar42]
Meter=BAR
BarColor=FAFAFA
MeasureName=MeasureAudioSmoothed43
X=(6 * 1)R
Y=0
W=(6 * 1)
H=(864 * 0.25)
BarOrientation=Vertical
[MeterBar43]
Meter=BAR
BarColor=FAFAFA
MeasureName=MeasureAudioSmoothed44
X=(6 * 1)R
Y=0
W=(6 * 1)
H=(864 * 0.25)
BarOrientation=Vertical
[MeterBar44]
Meter=BAR
BarColor=FAFAFA
MeasureName=MeasureAudioSmoothed45
X=(6 * 1)R
Y=0
W=(6 * 1)
H=(864 * 0.25)
BarOrientation=Vertical
[MeterBar45]
Meter=BAR
BarColor=FAFAFA
MeasureName=MeasureAudioSmoothed46
X=(6 * 1)R
Y=0
W=(6 * 1)
H=(864 * 0.25)
BarOrientation=Vertical
[MeterBar46]
Meter=BAR
BarColor=FAFAFA
MeasureName=MeasureAudioSmoothed47
X=(6 * 1)R
Y=0
W=(6 * 1)
H=(864 * 0.25)
BarOrientation=Vertical
[MeterBar47]
Meter=BAR
BarColor=FAFAFA
MeasureName=MeasureAudioSmoothed48
X=(6 * 1)R
Y=0
W=(6 * 1)
H=(864 * 0.25)
BarOrientation=Vertical
[MeterBar48]
Meter=BAR
BarColor=FAFAFA
MeasureName=MeasureAudioSmoothed49
X=(6 * 1)R
Y=0
W=(6 * 1)
H=(864 * 0.25)
BarOrientation=Vertical
[MeterBar49]
Meter=BAR
BarColor=FAFAFA
MeasureName=MeasureAudioSmoothed50
X=(6 * 1)R
Y=0
W=(6 * 1)
H=(864 * 0.25)
BarOrientation=Vertical
[MeterBar50]
Meter=BAR
BarColor=FAFAFA
MeasureName=MeasureAudioSmoothed51
X=(6 * 1)R
Y=0
W=(6 * 1)
H=(864 * 0.25)
BarOrientation=Vertical
[MeterBar51]
Meter=BAR
BarColor=FAFAFA
MeasureName=MeasureAudioSmoothed52
X=(6 * 1)R
Y=0
W=(6 * 1)
H=(864 * 0.25)
BarOrientation=Vertical
[MeterBar52]
Meter=BAR
BarColor=FAFAFA
MeasureName=MeasureAudioSmoothed53
X=(6 * 1)R
Y=0
W=(6 * 1)
H=(864 * 0.25)
BarOrientation=Vertical
[MeterBar53]
Meter=BAR
BarColor=FAFAFA
MeasureName=MeasureAudioSmoothed54
X=(6 * 1)R
Y=0
W=(6 * 1)
H=(864 * 0.25)
BarOrientation=Vertical
[MeterBar54]
Meter=BAR
BarColor=FAFAFA
MeasureName=MeasureAudioSmoothed55
X=(6 * 1)R
Y=0
W=(6 * 1)
H=(864 * 0.25)
BarOrientation=Vertical
[MeterBar55]
Meter=BAR
BarColor=FAFAFA
MeasureName=MeasureAudioSmoothed56
X=(6 * 1)R
Y=0
W=(6 * 1)
H=(864 * 0.25)
BarOrientation=Vertical
[MeterBar56]
Meter=BAR
BarColor=FAFAFA
MeasureName=MeasureAudioSmoothed57
X=(6 * 1)R
Y=0
W=(6 * 1)
H=(864 * 0.25)
BarOrientation=Vertical
[MeterBar57]
Meter=BAR
BarColor=FAFAFA
MeasureName=MeasureAudioSmoothed58
X=(6 * 1)R
Y=0
W=(6 * 1)
H=(864 * 0.25)
BarOrientation=Vertical
[MeterBar58]
Meter=BAR
BarColor=FAFAFA
MeasureName=MeasureAudioSmoothed59
X=(6 * 1)R
Y=0
W=(6 * 1)
H=(864 * 0.25)
BarOrientation=Vertical
[MeterBar59]
Meter=BAR
BarColor=FAFAFA
MeasureName=MeasureAudioSmoothed60
X=(6 * 1)R
Y=0
W=(6 * 1)
H=(864 * 0.25)
BarOrientation=Vertical
[MeterBar60]
Meter=BAR
BarColor=FAFAFA
MeasureName=MeasureAudioSmoothed61
X=(6 * 1)R
Y=0
W=(6 * 1)
H=(864 * 0.25)
BarOrientation=Vertical
[MeterBar61]
Meter=BAR
BarColor=FAFAFA
MeasureName=MeasureAudioSmoothed62
X=(6 * 1)R
Y=0
W=(6 * 1)
H=(864 * 0.25)
BarOrientation=Vertical
[MeterBar62]
Meter=BAR
BarColor=FAFAFA
MeasureName=MeasureAudioSmoothed63
X=(6 * 1)R
Y=0
W=(6 * 1)
H=(864 * 0.25)
BarOrientation=Vertical
[MeterBar63]
Meter=BAR
BarColor=FAFAFA
MeasureName=MeasureAudioSmoothed64
X=(6 * 1)R
Y=0
W=(6 * 1)
H=(864 * 0.25)
BarOrientation=Vertical
[MeterBar64]
Meter=BAR
BarColor=FAFAFA
MeasureName=MeasureAudioSmoothed65
X=(6 * 1)R
Y=0
W=(6 * 1)
H=(864 * 0.25)
BarOrientation=Vertical
[MeterBar65]
Meter=BAR
BarColor=FAFAFA
MeasureName=MeasureAudioSmoothed66
X=(6 * 1)R
Y=0
W=(6 * 1)
H=(864 * 0.25)
BarOrientation=Vertical
[MeterBar66]
Meter=BAR
BarColor=FAFAFA
MeasureName=MeasureAudioSmoothed67
X=(6 * 1)R
Y=0
W=(6 * 1)
H=(864 * 0.25)
BarOrientation=Vertical
[MeterBar67]
Meter=BAR
BarColor=FAFAFA
MeasureName=MeasureAudioSmoothed68
X=(6 * 1)R
Y=0
W=(6 * 1)
H=(864 * 0.25)
BarOrientation=Vertical
[MeterBar68]
Meter=BAR
BarColor=FAFAFA
MeasureName=MeasureAudioSmoothed69
X=(6 * 1)R
Y=0
W=(6 * 1)
H=(864 * 0.25)
BarOrientation=Vertical
[MeterBar69]
Meter=BAR
BarColor=FAFAFA
MeasureName=MeasureAudioSmoothed70
X=(6 * 1)R
Y=0
W=(6 * 1)
H=(864 * 0.25)
BarOrientation=Vertical
[MeterBar70]
Meter=BAR
BarColor=FAFAFA
MeasureName=MeasureAudioSmoothed71
X=(6 * 1)R
Y=0
W=(6 * 1)
H=(864 * 0.25)
BarOrientation=Vertical
[MeterBar71]
Meter=BAR
BarColor=FAFAFA
MeasureName=MeasureAudioSmoothed72
X=(6 * 1)R
Y=0
W=(6 * 1)
H=(864 * 0.25)
BarOrientation=Vertical
[MeterBar72]
Meter=BAR
BarColor=FAFAFA
MeasureName=MeasureAudioSmoothed73
X=(6 * 1)R
Y=0
W=(6 * 1)
H=(864 * 0.25)
BarOrientation=Vertical
[MeterBar73]
Meter=BAR
BarColor=FAFAFA
MeasureName=MeasureAudioSmoothed74
X=(6 * 1)R
Y=0
W=(6 * 1)
H=(864 * 0.25)
BarOrientation=Vertical
[MeterBar74]
Meter=BAR
BarColor=FAFAFA
MeasureName=MeasureAudioSmoothed75
X=(6 * 1)R
Y=0
W=(6 * 1)
H=(864 * 0.25)
BarOrientation=Vertical
[MeterBar75]
Meter=BAR
BarColor=FAFAFA
MeasureName=MeasureAudioSmoothed76
X=(6 * 1)R
Y=0
W=(6 * 1)
H=(864 * 0.25)
BarOrientation=Vertical
[MeterBar76]
Meter=BAR
BarColor=FAFAFA
MeasureName=MeasureAudioSmoothed77
X=(6 * 1)R
Y=0
W=(6 * 1)
H=(864 * 0.25)
BarOrientation=Vertical
[MeterBar77]
Meter=BAR
BarColor=FAFAFA
MeasureName=MeasureAudioSmoothed78
X=(6 * 1)R
Y=0
W=(6 * 1)
H=(864 * 0.25)
BarOrientation=Vertical
[MeterBar78]
Meter=BAR
BarColor=FAFAFA
MeasureName=MeasureAudioSmoothed79
X=(6 * 1)R
Y=0
W=(6 * 1)
H=(864 * 0.25)
BarOrientation=Vertical
[MeterBar79]
Meter=BAR
BarColor=FAFAFA
MeasureName=MeasureAudioSmoothed80
X=(6 * 1)R
Y=0
W=(6 * 1)
H=(864 * 0.25)
BarOrientation=Vertical
[MeterBar80]
Meter=BAR
BarColor=FAFAFA
MeasureName=MeasureAudioSmoothed81
X=(6 * 1)R
Y=0
W=(6 * 1)
H=(864 * 0.25)
BarOrientation=Vertical
[MeterBar81]
Meter=BAR
BarColor=FAFAFA
MeasureName=MeasureAudioSmoothed82
X=(6 * 1)R
Y=0
W=(6 * 1)
H=(864 * 0.25)
BarOrientation=Vertical
[MeterBar82]
Meter=BAR
BarColor=FAFAFA
MeasureName=MeasureAudioSmoothed83
X=(6 * 1)R
Y=0
W=(6 * 1)
H=(864 * 0.25)
BarOrientation=Vertical
[MeterBar83]
Meter=BAR
BarColor=FAFAFA
MeasureName=MeasureAudioSmoothed84
X=(6 * 1)R
Y=0
W=(6 * 1)
H=(864 * 0.25)
BarOrientation=Vertical
[MeterBar84]
Meter=BAR
BarColor=FAFAFA
MeasureName=MeasureAudioSmoothed85
X=(6 * 1)R
Y=0
W=(6 * 1)
H=(864 * 0.25)
BarOrientation=Vertical
[MeterBar85]
Meter=BAR
BarColor=FAFAFA
MeasureName=MeasureAudioSmoothed86
X=(6 * 1)R
Y=0
W=(6 * 1)
H=(864 * 0.25)
BarOrientation=Vertical
[MeterBar86]
Meter=BAR
BarColor=FAFAFA
MeasureName=MeasureAudioSmoothed87
X=(6 * 1)R
Y=0
W=(6 * 1)
H=(864 * 0.25)
BarOrientation=Vertical
[MeterBar87]
Meter=BAR
BarColor=FAFAFA
MeasureName=MeasureAudioSmoothed88
X=(6 * 1)R
Y=0
W=(6 * 1)
H=(864 * 0.25)
BarOrientation=Vertical
[MeterBar88]
Meter=BAR
BarColor=FAFAFA
MeasureName=MeasureAudioSmoothed89
X=(6 * 1)R
Y=0
W=(6 * 1)
H=(864 * 0.25)
BarOrientation=Vertical
[MeterBar89]
Meter=BAR
BarColor=FAFAFA
MeasureName=MeasureAudioSmoothed90
X=(6 * 1)R
Y=0
W=(6 * 1)
H=(864 * 0.25)
BarOrientation=Vertical
[MeterBar90]
Meter=BAR
BarColor=FAFAFA
MeasureName=MeasureAudioSmoothed91
X=(6 * 1)R
Y=0
W=(6 * 1)
H=(864 * 0.25)
BarOrientation=Vertical
[MeterBar91]
Meter=BAR
BarColor=FAFAFA
MeasureName=MeasureAudioSmoothed92
X=(6 * 1)R
Y=0
W=(6 * 1)
H=(864 * 0.25)
BarOrientation=Vertical
[MeterBar92]
Meter=BAR
BarColor=FAFAFA
MeasureName=MeasureAudioSmoothed93
X=(6 * 1)R
Y=0
W=(6 * 1)
H=(864 * 0.25)
BarOrientation=Vertical
[MeterBar93]
Meter=BAR
BarColor=FAFAFA
MeasureName=MeasureAudioSmoothed94
X=(6 * 1)R
Y=0
W=(6 * 1)
H=(864 * 0.25)
BarOrientation=Vertical
[MeterBar94]
Meter=BAR
BarColor=FAFAFA
MeasureName=MeasureAudioSmoothed95
X=(6 * 1)R
Y=0
W=(6 * 1)
H=(864 * 0.25)
BarOrientation=Vertical
[MeterBar95]
Meter=BAR
BarColor=FAFAFA
MeasureName=MeasureAudioSmoothed96
X=(6 * 1)R
Y=0
W=(6 * 1)
H=(864 * 0.25)
BarOrientation=Vertical
[MeterBar96]
Meter=BAR
BarColor=FAFAFA
MeasureName=MeasureAudioSmoothed97
X=(6 * 1)R
Y=0
W=(6 * 1)
H=(864 * 0.25)
BarOrientation=Vertical
[MeterBar97]
Meter=BAR
BarColor=FAFAFA
MeasureName=MeasureAudioSmoothed98
X=(6 * 1)R
Y=0
W=(6 * 1)
H=(864 * 0.25)
BarOrientation=Vertical
[MeterBar98]
Meter=BAR
BarColor=FAFAFA
MeasureName=MeasureAudioSmoothed99
X=(6 * 1)R
Y=0
W=(6 * 1)
H=(864 * 0.25)
BarOrientation=Vertical
[MeterBar99]
Meter=BAR
BarColor=FAFAFA
MeasureName=MeasureAudioSmoothed100
X=(6 * 1)R
Y=0
W=(6 * 1)
H=(864 * 0.25)
BarOrientation=Vertical