[Variables]
@include6=#@#MusiColor.inc
@include1=./MeasureAudio.inc

Mode=1
;Mode=1-5(5个模式：经典-流星-双环-WaveCC-万花筒)

Color=#MusiColorO#,([MR7M]*1000)

;整体颜色（RGB，只填一个数或者两个数有惊喜）

Xc=500
;Xc=#SCREENAREAWIDTH#  or  500（居中屏幕与否）

Amount=50
;45
;Amount=0-90（白条数量，偶数，适当调节有效降低占用）

InnerWidth=0
;内圈粗细（部分模式不适用）

InnerLength=0
;内圈长度（部分模式不适用）

OuterWidth=10
;外圈粗细（部分模式不适用）

OuterLength=-230
;外圈长度（部分模式不适用）

Time=0
;显示时间=1，隐藏时间=0，默认显示
TimeFont=方正兰亭超细黑简体

;保存后，鼠标滚轮点击，即可刷新

Color=0,0,0,0
